# Generated by Django 5.2.10 on 2026-02-14 15:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadMetadata',
            fields=[
                ('upload_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('total_chunks', models.IntegerField()),
                ('uploaded_chunks', models.IntegerField(default=0)),
                ('size', models.BigIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UPLOADING', 'Uploading'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
