# Generated by Django 5.2.10 on 2026-02-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmetadata',
            name='offset',
            field=models.IntegerField(default=0),
        ),
    ]
