# Generated by Django 5.2.10 on 2026-03-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_uploadmetadata_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmetadata',
            name='file_path',
            field=models.CharField(default='viks', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadmetadata',
            name='uploaded_bytes',
            field=models.BigIntegerField(default=100),
            preserve_default=False,
        ),
    ]
