# Generated by Django 5.2.10 on 2026-03-04 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_uploadmetadata_file_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadmetadata',
            name='uploaded_bytes',
        ),
        migrations.RemoveField(
            model_name='uploadmetadata',
            name='uploaded_chunks',
        ),
    ]
